<div class="container mb-2">
    <nav class="navbar navbar-expand bg-body-tertiary">
        <div class="collapse navbar-collapse">
            <a class="navbar-brand" href="/">To Do App</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="/tasks">Tasks</a>
                </li>
            </ul>
        </div>
        <?php
        if (isset($adminName)) : ?>
        <div class="d-flex">
            <div class="d-flex flex-column justify-content-center ms-1 me-2">
                <div class="text-end small text-secondary"
                <span>You have signed in as</span>
                <span class=" fw-bold">
                            <?= htmlspecialchars($adminName) ?>
                        </span>
            </div>
        </div>
        <form method="post" class="session-delete" action="/sessions">
            <input type="hidden" name="_method" value="delete"/>
            <button type="submit" class="btn btn-outline-secondary">Sign Out
            </button>
        </form>
</div>
<?php
else : ?>
    <a class="session-new" href="/sessions/new">
        <button type="submit" class="btn btn-secondary">Sign In</button>
    </a>
<?php
endif ?>
</nav>
</div>



