version: '3'
services:

  #Nginx Server
  webserver:
    image: nginx
    container_name: "${PREFIX}webserver"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - php

  #PHP
  php:
    build:
      context: images/php
    container_name: "${PREFIX}php"
    env_file:
      - .env
    volumes:
      - ./public:/var/www/public
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./vendor:/var/www/vendor
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      pgsql:
        condition: service_healthy

  #PostgreSQL
  pgsql:
    image: postgres
    container_name: "${PREFIX}postgresql"
    ports:
      - "${PGSQL_PORT}:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./scripts/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "${PGSQL_USER}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DB}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
