<div class="row justify-content-md-center">
    <div class="col-12 col-md-6 col-lg-4">
        <div class="card mb-3">
            <div class="card-body">
                <h1 class="h2 text-center">Editing the task</h1>

                <table class="table align-middle">
                    <tr>
                        <td>User name</td>
                        <td><?= htmlspecialchars($task->getUserName()) ?></td>
                    </tr>
                    <tr>
                        <td>User email</td>
                        <td><?= htmlspecialchars($task->getUserEmail()) ?></td>
                    </tr>
                    <tr>
                        <td>Created At</td>
                        <td><?= htmlspecialchars(
                                $task->getCreatedAt()->format('Y-m-d H:i:s')
                            ) ?></td>
                    </tr>
                </table>

                <form action="/tasks/<?= htmlspecialchars(
                    $task->getId()
                ) ?>" method="post">
                    <input type="hidden" name="_method" value="put">
                    <div class="mb-3">
                        <label for="DescriptionTextarea"
                               class="form-label">Description</label>
                        <textarea
                                class="form-control"
                                rows="5"
                                id="DescriptionTextarea"
                                name="description"><?= htmlspecialchars(
                                $task->getDescription()
                            ) ?>
                        </textarea>
                    </div>

                    <div class="mb-3">
                        <div class="form-check">
                            <input
                                    class="form-check-input"
                                    type="checkbox"
                                    value=""
                                    id="inputIsDone"
                                    name="isDone"
                                <?php
                                if ($task->isDone()) : ?>
                                    checked
                                <?php
                                endif ?>
                            >
                            <label class="form-check-label"
                                   for="inputIsDone">
                                Mark the task as done
                            </label>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">
                            Save changes
                        </button>
                    </div>
                </form>

            </div>
        </div>
        <?php
        require_once '/var/www/src/templates/_errors.phtml' ?>
    </div>
</div>
