<?php

use App\Dto\SortingCriterion as Sc;
use App\Dto\SortingOrder as So;

?>

<div class="row">
    <div class="col">
        <h1 class="mb-3">Tasks</h1>
        <div class="mb-3">
            <a href="/tasks/new">
                <button class="btn btn-primary">Add new task</button>
            </a>
        </div>

        <?php
        require_once '/var/www/src/templates/_errors.phtml' ?>

        <table class="table table-striped align-middle">
            <tr class="align-top">
                <th class="col-1">
                    <?php
                    if ($sortBy === Sc::CREATED_AT) { ?>
                        <?php
                        if ($orderBy === So::ASC) { ?>
                            <a href="/tasks?sort=<?= Sc::CREATED_AT->value ?>&order=<?= So::DESC->value ?>">
                                Created At &#9660;
                            </a>
                            <?php
                        } else { ?>
                            <a href="/tasks?sort=<?= Sc::CREATED_AT->value ?>&order=<?= So::ASC->value ?>">
                                Created At &#9650;
                            </a>
                            <?php
                        } ?>
                        <?php
                    } else { ?>
                        <a href="/tasks?sort=<?= Sc::CREATED_AT->value ?>&order=<?= So::ASC->value ?>">
                            Created At
                        </a>
                        <?php
                    } ?>
                </th>
                <th class="col-1">
                    <?php
                    if ($sortBy === Sc::USER_NAME) { ?>
                        <?php
                        if ($orderBy === So::ASC) { ?>
                            <a href="/tasks?sort=<?= Sc::USER_NAME->value ?>&order=<?= So::DESC->value ?>">
                                User name &#9660;
                            </a>
                            <?php
                        } else { ?>
                            <a href="/tasks?sort=<?= Sc::USER_NAME->value ?>&order=<?= So::ASC->value ?>">
                                User name &#9650;
                            </a>
                            <?php
                        } ?>
                        <?php
                    } else { ?>
                        <a href="/tasks?sort=<?= Sc::USER_NAME->value ?>&order=<?= So::ASC->value ?>">
                            User name
                        </a>
                        <?php
                    } ?>
                </th>
                <th class="col-3">
                    <?php
                    if ($sortBy === Sc::USER_EMAIL) { ?>
                        <?php
                        if ($orderBy === So::ASC) { ?>
                            <a href="/tasks?sort=<?= Sc::USER_EMAIL->value ?>&order=<?= So::DESC->value ?>">
                                User email &#9660;
                            </a>
                            <?php
                        } else { ?>
                            <a href="/tasks?sort=<?= Sc::USER_EMAIL->value ?>&order=<?= So::ASC->value ?>">
                                User email &#9650;
                            </a>
                            <?php
                        } ?>
                        <?php
                    } else { ?>
                        <a href="/tasks?sort=<?= Sc::USER_EMAIL->value ?>&order=<?= So::ASC->value ?>">
                            User email
                        </a>
                        <?php
                    } ?>
                </th>
                <th class="col-4">
                    <?php
                    if ($sortBy === Sc::DESCRIPTION) { ?>
                        <?php
                        if ($orderBy === So::ASC) { ?>
                            <a href="/tasks?sort=<?= Sc::DESCRIPTION->value ?>&order=<?= So::DESC->value ?>">
                                Description &#9660;
                            </a>
                            <?php
                        } else { ?>
                            <a href="/tasks?sort=<?= Sc::DESCRIPTION->value ?>&order=<?= So::ASC->value ?>">
                                Description &#9650;
                            </a>
                            <?php
                        } ?>
                        <?php
                    } else { ?>
                        <a href="/tasks?sort=<?= Sc::DESCRIPTION->value ?>&order=<?= So::ASC->value ?>">
                            Description
                        </a>
                        <?php
                    } ?>
                </th>
                <th>
                    <?php
                    if ($sortBy === Sc::IS_DONE) { ?>
                        <?php
                        if ($orderBy === So::ASC) { ?>
                            <a href="/tasks?sort=<?= Sc::IS_DONE->value ?>&order=<?= So::DESC->value ?>">
                                Status &#9660;
                            </a>
                            <?php
                        } else { ?>
                            <a href="/tasks?sort=<?= Sc::IS_DONE->value ?>&order=<?= So::ASC->value ?>">
                                Status &#9650;
                            </a>
                            <?php
                        } ?>
                        <?php
                    } else { ?>
                        <a href="/tasks?sort=<?= Sc::IS_DONE->value ?>&order=<?= So::ASC->value ?>">
                            Status
                        </a>
                        <?php
                    } ?>
                </th>
                <?php
                if (isset($adminName)) : ?>
                    <th colspan="2" class="text-center">Actions</th>
                <?php
                endif ?>
            </tr>
            <?php
            if (isset($tasks)) : ?>
                <?php
                foreach ($tasks as $task) : ?>
                    <tr>
                        <td>
                            <?= htmlspecialchars(
                                $task->getCreatedAt()->format('Y-m-d H:i:s')
                            ) ?>
                        </td>
                        <td>
                            <?= htmlspecialchars($task->getUserName()) ?>
                        </td>
                        <td>
                            <?= htmlspecialchars($task->getUserEmail()) ?>
                        </td>
                        <td>
                            <?= htmlspecialchars($task->getDescription()) ?>
                        </td>

                        <?php
                        if ($task->isDone()) : ?>
                            <td class="text-success">
                                DONE
                            </td>
                        <?php
                        else : ?>
                            <td class="text-primary">
                                CREATED
                            </td>
                        <?php
                        endif ?>

                        <?php
                        if (isset($adminName)) : ?>
                            <td>
                                <a href="/tasks/<?= htmlspecialchars(
                                    $task->getId()
                                ) ?>/edit">
                                    <button class="btn btn-outline-primary">
                                        Edit
                                    </button>
                                </a>
                            </td>
                            <td>
                                <button type="button"
                                        class="btn btn-outline-danger"
                                        data-bs-toggle="modal"
                                        data-bs-target="#exampleModal<?= htmlspecialchars(
                                            $task->getId()
                                        ) ?>">
                                    Delete
                                </button>
                                <div class="modal fade"
                                     id="exampleModal<?= htmlspecialchars(
                                         $task->getId()
                                     ) ?>"
                                     tabindex="-1"
                                     aria-labelledby="exampleModalLabel"
                                     aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title"
                                                    id="exampleModalLabel">
                                                    Warning</h5>
                                                <button type="button"
                                                        class="btn-close"
                                                        data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure you want to delete
                                                the task?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button"
                                                        class="btn btn-secondary"
                                                        data-bs-dismiss="modal">
                                                    Cancel
                                                </button>
                                                <form class="form"
                                                      action="/tasks/<?= htmlspecialchars(
                                                          $task->getId()
                                                      ) ?>"
                                                      method="post">
                                                    <input type="hidden"
                                                           name="_method"
                                                           value="delete">
                                                    <div class="text-center">
                                                        <button type="submit"
                                                                class="btn btn-danger">
                                                            Delete
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        <?php
                        endif ?>
                    </tr>
                <?php
                endforeach ?>
            <?php
            endif ?>
        </table>

        <?php
        if ($pageTotalCount > 1) : ?>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <?php
                    if ($currentPage > 3) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=1">
                                1
                            </a>
                        </li>
                    <?php
                    endif ?>
                    <?php
                    if ($currentPage > 4) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage
                               - 3 ?>">
                                ...
                            </a>
                        </li>
                    <?php
                    endif ?>
                    <?php
                    if ($currentPage - 2 > 0) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage
                               - 2 ?>">
                                <?= $currentPage - 2 ?></a>
                        </li>
                    <?php
                    endif ?>
                    <?php
                    if ($currentPage - 1 > 0) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage
                               - 1 ?>">
                                <?= $currentPage - 1 ?>
                            </a>
                        </li>
                    <?php
                    endif ?>
                    <li class="page-item active">
                        <a class="page-link"
                           href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage ?>">
                            <?= $currentPage ?>
                        </a>
                    </li>
                    <?php
                    if ($currentPage + 1 < $pageTotalCount) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage
                               + 1 ?>">
                                <?= $currentPage + 1 ?>
                            </a>
                        </li>
                    <?php
                    endif ?>
                    <?php
                    if ($currentPage + 2 < $pageTotalCount) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage
                               + 2 ?>">
                                <?= $currentPage + 2 ?>
                            </a>
                        </li>
                    <?php
                    endif ?>

                    <?php
                    if ($currentPage + 3 < $pageTotalCount) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $currentPage
                               + 3 ?>">
                                ...
                            </a>
                        </li>
                    <?php
                    endif ?>

                    <?php
                    if ($currentPage < $pageTotalCount) : ?>
                        <li class="page-item">
                            <a class="page-link"
                               href="/tasks?sort=<?= $sortBy->value ?>&order=<?= $orderBy->value ?>&page=<?= $pageTotalCount ?>">
                                <?= $pageTotalCount ?>
                            </a>
                        </li>
                    <?php
                    endif ?>
                </ul>
            </nav>
        <?php
        endif ?>
    </div>
</div>







