<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tasks</title>
    <link rel="shortut icon" href="/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">
</head>

<body>
<div class="container mb-2">
    <nav class="navbar navbar-expand bg-body-tertiary">
        <div class="collapse navbar-collapse">
            <a class="navbar-brand" href="/">To Do App</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="/tasks">Tasks</a>
                </li>
            </ul>
        </div>
        <?php
        if (isset($adminName)) : ?>
            <div class="d-flex">
                <div class="d-flex flex-column justify-content-center ms-1 me-2">
                    <div class="text-end small text-secondary"
                    <span>You have signed in as</span>
                    <span class=" fw-bold">
                            <?= htmlspecialchars($adminName) ?>
                        </span>
                </div>
            </div>
            <form method="post" class="session-delete" action="/sessions">
                <input type="hidden" name="_method" value="delete"/>
                <button type="submit" class="btn btn-outline-secondary">Sign Out
                </button>
            </form>
        <?php
        else : ?>
            <a class="session-new" href="/sessions/new">
                <button type="submit" class="btn btn-secondary">Sign In</button>
            </a>
        <?php
        endif ?>
    </nav>
</div>

<div class="container">
    <?= $this->html ?>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>
</html>