<div class="row justify-content-md-center">
    <div class="col-12 col-md-6 col-lg-4">
        <div class="card mb-3">
            <div class="card-body">
                <h1 class="h2 text-center">Adding a new task</h1>
                <form action="/tasks" method="post">
                    <div class="mb-3">
                        <label for="inputUserName" class="form-label">User
                            name</label>
                        <input type="text" class="form-control"
                               id="inputUserName" name="userName">
                    </div>
                    <div class="mb-3">
                        <label for="inputUserEmail" class="form-label">User
                            email</label>
                        <input type="email" class="form-control"
                               id="inputUserEmail" name="userEmail">
                    </div>

                    <div class="mb-3">
                        <div class="mb-3">
                            <label for="inputDescription"
                                   class="form-label">Description</label>
                            <input type="text" class="form-control"
                                   id="inputDescription"
                                   name="description">
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">
                            Confirm
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <?php
        require_once '/var/www/app/templates/_errors.phtml' ?>
    </div>
</div>
